feat: meny typo - copy Trainings replace by Training
cyfronet-fid/eosc-search-service pull request #1105
Opened 2023-12-07 11:27 UTC by Anok666

2023-12-07 11:58 UTC, agpul requested changes
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/43000481/41e0f61d-0467-47a6-b64a-9f70e32350cf)
lack of logo for Training

2023-12-07 12:09 UTC, maria-j-k approved these changes

2023-12-12 11:14 UTC, Marcelinna approved these changes

2023-12-12 12:34 UTC, eldenkat approved these changes

2023-12-13 10:10 UTC, agpul approved these changes

2023-12-13 10:36 UTC, merged