fix: none-of and exact search in providers
cyfronet-fid/eosc-search-service pull request #1211
Opened 2024-02-19 17:46 UTC by maria-j-k

closes #1210

2024-02-21 09:08 UTC, tomaszandel approved these changes

2024-03-01 15:56 UTC, Michal-Kolomanski commented
@agpul 
@jarekzet is needed to style (to match previous design):
<img width="765" alt="image" src="https://github.com/cyfronet-fid/eosc-search-service/assets/47147210/82916df4-e131-4d2b-84e7-19931f671d15">

2024-03-01 16:20 UTC, Michal-Kolomanski requested changes
Lets stay with DOI as tag, and fix AS filter bug

2024-03-04 12:34 UTC, Michal-Kolomanski approved these changes
That is really good code! 👏 Props for simplifying and abstracting the code.

@Marcelinna @agpul, we need to test really carefully the whole advanced search. There may be some hidden regressions

2024-03-05 13:50 UTC, Marcelinna commented
pr - I don't see highlight for DOI
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/59872096/30d8a3f3-f155-4f10-a669-958027bb684e)
beta
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/59872096/78184424-d20a-44fd-a0b8-4a4331d61a69)

2024-03-05 15:09 UTC, Marcelinna commented
pr
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/59872096/2e2045d7-78f9-4066-a255-a846b48b4f65)
beta
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/59872096/1b71d116-cbfb-4fa4-a2c0-88928f6cc912)

2024-03-14 10:27 UTC, Marcelinna approved these changes

2024-03-14 10:35 UTC, merged