1235 right side panel
cyfronet-fid/eosc-search-service pull request #1253
Opened 2024-02-28 10:05 UTC by jarekzet

Changes due to #1235 

![image](https://github.com/cyfronet-fid/eosc-search-service/assets/8420566/cf82583e-1cd4-4015-829e-e5094f3332a7)

2024-02-28 17:15 UTC, jarekzet commented
Deleted hover animations, added new hover effects and added modifications to elements heights.

2024-02-29 09:14 UTC, Marcelinna approved these changes

2024-02-29 16:37 UTC, Michal-Kolomanski commented on ui/apps/ui/src/app/components/articles/articles.component.ts
> +      url: `https://beta.knowledge-hub.eosc-portal.eu/ `,
Do we want to redirect always to the beta knowledge hub?

2024-02-29 16:39 UTC, Michal-Kolomanski commented on ui/apps/ui/src/app/pages/search-page/search-page.component.html
> +              <a href="https://beta.knowledge-hub.eosc-portal.eu/articles/article_01.html">
the same question. I assume that currently there is no production version of that site, but shouldn't it be dynamically assigned?

2024-02-29 16:46 UTC, Michal-Kolomanski commented on ui/apps/ui/src/app/components/articles/articles.component.ts
> +      url: `https://beta.knowledge-hub.eosc-portal.eu/ `,
Please replace that with a variable `KNOWLEDGE_HUB_URL`: https://github.com/cyfronet-fid/eosc-search-service/blob/eb3bbd0b19bcc978eb949794a75cd251b49c701b/README.md?plain=1#L185

2024-02-29 16:48 UTC, Michal-Kolomanski requested changes
Link needs to be dynamically assigned

2024-02-29 16:48 UTC, Michal-Kolomanski commented on ui/apps/ui/src/app/components/articles/articles.component.ts
> +      url: `https://beta.knowledge-hub.eosc-portal.eu/ `,
Please replace that with a variable `KNOWLEDGE_HUB_URL`: https://github.com/cyfronet-fid/eosc-search-service/blob/eb3bbd0b19bcc978eb949794a75cd251b49c701b/README.md?plain=1#L185

2024-02-29 16:48 UTC, Michal-Kolomanski commented on ui/apps/ui/src/app/pages/search-page/search-page.component.html
> +              <a href="https://beta.knowledge-hub.eosc-portal.eu/articles/article_01.html">
Construct a link using `KNOWLEDGE_HUB_URL`: https://github.com/cyfronet-fid/eosc-search-service/blob/eb3bbd0b19bcc978eb949794a75cd251b49c701b/README.md?plain=1#L185

2024-02-29 16:48 UTC, Michal-Kolomanski commented on ui/apps/ui/src/app/pages/search-page/search-page.component.html
> +              <a href="https://beta.knowledge-hub.eosc-portal.eu/articles/article_02.html">
Construct a link using `KNOWLEDGE_HUB_URL`: https://github.com/cyfronet-fid/eosc-search-service/blob/eb3bbd0b19bcc978eb949794a75cd251b49c701b/README.md?plain=1#L185

2024-02-29 16:48 UTC, Michal-Kolomanski commented on ui/apps/ui/src/app/pages/search-page/search-page.component.html
> +              <a href="https://beta.knowledge-hub.eosc-portal.eu/articles/article_03.html">
Construct a link using `KNOWLEDGE_HUB_URL`: https://github.com/cyfronet-fid/eosc-search-service/blob/eb3bbd0b19bcc978eb949794a75cd251b49c701b/README.md?plain=1#L185

2024-02-29 16:48 UTC, Michal-Kolomanski commented on ui/apps/ui/src/app/pages/search-page/search-page.component.html
> +          <a href="https://beta.marketplace.eosc-portal.eu/user_documentation" class="right-media-link">
construct a link using MARKETPLACE_BASE_URL
https://github.com/cyfronet-fid/eosc-search-service/blob/eb3bbd0b19bcc978eb949794a75cd251b49c701b/README.md?plain=1#L179

2024-03-01 14:28 UTC, Marcelinna commented
@maria-j-k Please change article name similar to beta
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/59872096/62d924b2-21ed-46b6-99e9-3a032ef27284)

2024-03-01 15:34 UTC, Michal-Kolomanski approved these changes

2024-03-04 06:32 UTC, merged