fix: [#1367] fix db oag scheme
cyfronet-fid/eosc-search-service pull request #1370
Opened 2024-08-28 12:24 UTC by wiktorflorian

2024-08-28 14:03 UTC, Michal-Kolomanski requested changes

2024-08-28 16:55 UTC, wiktorflorian commented on transform/schemas/common/oag/instance.py
> +    measures: Optional[List[KeyValueModel]]  # TODO: check if this exists
Deleted

2024-08-28 16:56 UTC, wiktorflorian commented on transform/schemas/db/dataset.py
> +# TODO: implement connection between organisation, author, collected_from, context, instance, projects, relations and subject
ok, removed

2024-08-28 17:00 UTC, wiktorflorian commented on transform/schemas/db/oag/__init__.py
that's right

2024-08-29 09:49 UTC, Michal-Kolomanski approved these changes
:clap

2024-08-29 10:39 UTC, merged