feat: add keywords to results (WIP)
cyfronet-fid/eosc-search-service pull request #342
Opened 2022-11-14 12:09 UTC by danielkryska

2022-11-14 12:12 UTC, danielkryska commented
![image](https://user-images.githubusercontent.com/31220811/201657001-5d5cb4e7-4e4f-4918-b1d3-f806737f870e.png)
![image](https://user-images.githubusercontent.com/31220811/201657065-78848376-4fce-4ced-a474-40e0552d8439.png)
![image](https://user-images.githubusercontent.com/31220811/201657119-0d9011a2-c69f-4f39-ade1-915f546fa452.png)
![image](https://user-images.githubusercontent.com/31220811/201657198-b30a46a8-88d5-4517-9992-4dd95795c10f.png)

2022-11-15 08:06 UTC, danielkryska commented
![image](https://user-images.githubusercontent.com/31220811/201863353-f325bda7-88fd-4dfb-b0a5-8bbd35a0d4aa.png)

2022-11-15 08:06 UTC, danielkryska commented
![image](https://user-images.githubusercontent.com/31220811/201863789-5fe5c943-2225-4762-8b76-889a270fbacd.png)

2022-11-15 10:19 UTC, michal-szostak approved these changes

2022-11-15 15:37 UTC, agpul requested changes
1. Why I am not able to filter by "tags" in Services and Data sources? I should be able to.
2.  Please remove keywords duplication from the Training view:

![image](https://user-images.githubusercontent.com/43000481/201961039-881477c3-3cec-43e7-aa1a-c0df50a83f7e.png)

---

1. fixed
2. removed


![image](https://user-images.githubusercontent.com/31220811/202165326-89d838f5-bb41-4ca3-8472-a4b0b8f97aa5.png)

2022-11-15 16:23 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV
When I click on keyword for Services or Data sources in All catalogs tab
![image](https://user-images.githubusercontent.com/59872096/201972125-d6bb2f7e-6438-413d-8a99-8346de68b4a8.png)

2022-11-17 08:59 UTC, Marcelinna commented
Can we block adding multiple time the same filtr
![image](https://user-images.githubusercontent.com/59872096/202401917-77c136bb-ce3f-4d77-a2ad-560681db8a4a.png)

2022-11-17 09:31 UTC, Marcelinna approved these changes

2022-11-18 07:56 UTC, Marcelinna approved these changes

2022-11-18 09:37 UTC, michal-szostak commented on ui/apps/ui/src/app/collections/data/data-sources/adapter.data.ts
> +    ],
I think this should be a separate function (similar to `parseStatistics(...)`

2022-11-18 09:37 UTC, michal-szostak approved these changes

2022-11-18 09:45 UTC, merged