feat: search improvements for #404 and #397 and #319
cyfronet-fid/eosc-search-service pull request #435
Opened 2023-02-06 15:38 UTC by tomaszandel

- search improvement
- tested on http://149.156.182.2:8983/solr and with NON facade recommender.

-goal: set KeywordTokenizer and add simple algo for KeywordTokenizer with ~2 maximum if more than 3 words with words size greater than 5. otherwise no fuzzy. case for ~1 also to be crafted. Important with KeywordTokenizer would be to add mm at 70-80%.

2023-02-07 08:38 UTC, agpul commented
Use case: Datasource: "MetalPDB: a database of metal-binding sites in 3D structures of biological macromolecules"
1. Type: "a database of metal-binding"
- metal-binding is changed to metalbinding and it is not found
- the word "a" causes a lot of problems because the search engine is looking for single "a"
![image](https://user-images.githubusercontent.com/43000481/217193701-7021cfcc-df59-402d-87e3-2739c99c71b7.png)

2023-02-07 08:47 UTC, agpul commented
> Use case: Datasource: "MetalPDB: a database of metal-binding sites in 3D structures of biological macromolecules"
> 
> 1. Type: "a database of metal-binding"
> 
> * metal-binding is changed to metalbinding and it is not found
> * the word "a" causes a lot of problems because the search engine is looking for single "a"
>   ![image](https://user-images.githubusercontent.com/43000481/217193701-7021cfcc-df59-402d-87e3-2739c99c71b7.png)

maybe we should not take into consideration short words like "a", "of" etc... is it possible?

2023-02-07 09:53 UTC, agpul commented
Remove: 
![image](https://user-images.githubusercontent.com/43000481/217211370-3387fa81-157d-40b7-8caa-328d4ab70dc9.png)

2023-02-07 09:56 UTC, agpul commented
Just a question: 
![image](https://user-images.githubusercontent.com/43000481/217211949-2373c7a8-e063-421e-8a29-f927ec26cdb1.png)
What do you think, what should be more important: August x2 or "August 1964" - for me "August 1964":)

2023-02-07 09:59 UTC, agpul commented
> Just a question: ![image](https://user-images.githubusercontent.com/43000481/217211949-2373c7a8-e063-421e-8a29-f927ec26cdb1.png) What do you think, what should be more important in this case: August x2 or "August 1964" ?- for me "August 1964":)

Or maybe we should add the support for ""? In case of such typing: 
![image](https://user-images.githubusercontent.com/43000481/217212992-4d90babf-72ce-4a9c-98f6-dc7312dcece0.png)
we should have "August 1964" on the top.

2023-02-07 10:16 UTC, eldenkat commented
![2023-02-07 (1)](https://user-images.githubusercontent.com/113451713/217217010-81978f42-75c2-4d43-9628-0d3ffc3738ba.png)
###

2023-02-07 10:21 UTC, agpul commented
> ![2023-02-07 (1)](https://user-images.githubusercontent.com/113451713/217217010-81978f42-75c2-4d43-9628-0d3ffc3738ba.png)

@eldenkat what is the problem here?

2023-02-07 10:29 UTC, agpul commented
I type: Sleeping site selection in two Asian viverrids: effects of predation risk, resource access and habitat characteristics"

why "habitat characteristics" is not highlighted in the title but is highlighted in the description?:)
![image](https://user-images.githubusercontent.com/43000481/217219933-9db18648-380c-475f-983c-459fba35ddd8.png)

2023-02-07 10:31 UTC, agpul commented
> > ![2023-02-07 (1)](https://user-images.githubusercontent.com/113451713/217217010-81978f42-75c2-4d43-9628-0d3ffc3738ba.png)
> 
> @eldenkat what is the problem here? Seems odd, no name, no title, three times the same position. What does it say to the user?

I think that it is not a scope of this issue because the search engine works properly - it is not the blame of the search engine it is the blame of OpenAire data, but @tomaszandel can confirm or reject:P

2023-02-07 10:32 UTC, eldenkat commented
Do author and title carry the same importance when searching by typed word? @agpul

2023-02-07 10:48 UTC, eldenkat commented
make the clear all button opaque?
![2023-02-07 (4)](https://user-images.githubusercontent.com/113451713/217224298-c4fb9749-d91c-4055-a550-6c37b8d1e10e.png)

2023-02-07 11:09 UTC, eldenkat requested changes
Pagination does not work when results are listed on more than one page

2023-02-07 12:10 UTC, eldenkat commented
No highlights in trainings. Other categories shows higlights in the same search case.
![2023-02-07 (8)](https://user-images.githubusercontent.com/113451713/217241448-b0094349-8234-4d56-8a62-87ed6ddf8756.png)

2023-02-07 12:49 UTC, eldenkat commented
SS does not display a search result for the query from the first item in the list.
![2023-02-07 (10)](https://user-images.githubusercontent.com/113451713/217249248-fec5a46c-9ad9-475c-a8a6-ff8d3f61dbd6.png)

2023-02-07 13:54 UTC, Marcelinna commented
Why [Bouchaib Bahli] is higer than [Maksi Bouchaib]
![image](https://user-images.githubusercontent.com/59872096/217264186-d8e40437-7200-465f-9ce1-ccf93efec682.png)

2023-02-07 13:56 UTC, Marcelinna commented
I am not sure that autocomplete works fine
![image](https://user-images.githubusercontent.com/59872096/217264824-972ba8c8-2599-4399-9362-93ee4f0fcb85.png)

2023-02-07 18:31 UTC, tomaszandel commented
> Just a question: ![image](https://user-images.githubusercontent.com/43000481/217211949-2373c7a8-e063-421e-8a29-f927ec26cdb1.png) What do you think, what should be more important in this case: August x2 or "August 1964" ?- for me "August 1964":)

Yes, this is why keywordTokenizer is probably better idea, it shoudl match whole sentences better,  but in some other cases it will lack search flexibility ;)

2023-02-07 18:37 UTC, tomaszandel commented
> > Use case: Datasource: "MetalPDB: a database of metal-binding sites in 3D structures of biological macromolecules"
> > 
> > 1. Type: "a database of metal-binding"
> > 
> > 
> > * metal-binding is changed to metalbinding and it is not found
> > * the word "a" causes a lot of problems because the search engine is looking for single "a"
> >   ![image](https://user-images.githubusercontent.com/43000481/217193701-7021cfcc-df59-402d-87e3-2739c99c71b7.png)
> 
> maybe we should not take into consideration short words like "a", "of" etc... is it possible?

Solr is returning that values properly, bug is on our side, we match the regex wrongly, thus it highlights every occurence, fix TODO

2023-02-07 18:44 UTC, tomaszandel commented
> > Just a question: ![image](https://user-images.githubusercontent.com/43000481/217211949-2373c7a8-e063-421e-8a29-f927ec26cdb1.png) What do you think, what should be more important in this case: August x2 or "August 1964" ?- for me "August 1964":)
> 
> Or maybe we should add the support for ""? In case of such typing: ![image](https://user-images.githubusercontent.com/43000481/217212992-4d90babf-72ce-4a9c-98f6-dc7312dcece0.png) we should have "August 1964" on the top.

hmm in fact it is correct according to our setup, 2 matched names gets higher score, so its technically OK. TO fix it we should consider a separate call like you mention " " that looks for 100% whole sentence match. Or just field selection where search would look for

2023-02-07 18:47 UTC, tomaszandel commented
> > Use case: Datasource: "MetalPDB: a database of metal-binding sites in 3D structures of biological macromolecules"
> > 
> > 1. Type: "a database of metal-binding"
> > 
> > 
> > * metal-binding is changed to metalbinding and it is not found
> > * the word "a" causes a lot of problems because the search engine is looking for single "a"
> >   ![image](https://user-images.githubusercontent.com/43000481/217193701-7021cfcc-df59-402d-87e3-2739c99c71b7.png)
> 
> maybe we should not take into consideration short words like "a", "of" etc... is it possible?

- we can fix, we should make a list of separators we want to let in, when i remove - search works properly

2023-02-07 18:52 UTC, tomaszandel commented
> I type: Sleeping site selection in two Asian viverrids: effects of predation risk, resource access and habitat characteristics"
> 
> why "habitat characteristics" is not highlighted in the title but is highlighted in the description?:) ![image](https://user-images.githubusercontent.com/43000481/217219933-9db18648-380c-475f-983c-459fba35ddd8.png)

This is interesting case, because solr indeed is not highlighting it in title, but its a bit more complicated how he chooses what and what not to highlight, we could fix it on our end as we are using regex match, however why solr is not highlighting it is a mystery :)

2023-02-07 19:02 UTC, tomaszandel commented
> Do author and title carry the same importance when searching by typed word? @agpul ![image](https://user-images.githubusercontent.com/59872096/217256796-03ea7365-4b0d-408f-a3a4-f2176f69c433.png) ![image](https://user-images.githubusercontent.com/59872096/217257288-7eec352b-b065-4fd1-a91d-73648e01b513.png)
> 
> which result should be higher? or should have the same weight

Yeah this is tricky, if want to locate by author names, author has to be boosted higher, otherwise simple names in many cases exists in titles, same with surnames. So its a tradeoff, ideally we should have a field selection in search that would fix everything

2023-02-07 19:12 UTC, tomaszandel commented
> No highlights in trainings. Other categories show higlights in the same search case.
> 
> ![2023-02-07 (8)](https://user-images.githubusercontent.com/113451713/217241448-b0094349-8234-4d56-8a62-87ed6ddf8756.png)

yeah it seems its a case not handled on our end, trainings are not highlighed at all, its a valid bug, solr replies correctly here

2023-02-07 19:17 UTC, tomaszandel commented
> I am not sure that autocomplete works fine ![image](https://user-images.githubusercontent.com/59872096/217264824-972ba8c8-2599-4399-9362-93ee4f0fcb85.png)

It is ok, remember that this is not really an autocomplete, because it searches title, descrition, authors, keywords and so on, if we want to have a real autocomplete for titles than we should search only in titles, or display 'autocomplete' tool differently, so we can see what is matching, here we show only titles, but matches could be in some other place, 

<img width="676" alt="Zrzut ekranu 2023-02-7 o 23 14 29" src="https://user-images.githubusercontent.com/11340871/217343085-267ac9e5-d0ea-4f90-a3ae-2bd83e7567a8.png">

2023-02-12 20:24 UTC, Marcelinna commented
I type "INDIGO Identity and Access Management (IAM)", when I am on page 1 
![image](https://user-images.githubusercontent.com/59872096/218335082-bfb77ecf-72c0-4039-a6e7-cc98dc437a69.png)
I type "INDIGO Identity and Access Management (IAM)", when I am on page 6
![image](https://user-images.githubusercontent.com/59872096/218335190-8d57f229-301c-481a-af52-10e763dd4fc3.png)

2023-02-13 09:46 UTC, Michal-Kolomanski approved these changes
LGTM

2023-02-13 09:46 UTC, Michal-Kolomanski commented on backend/app/routes/web/search.py
> +        except Exception as e:
Too broad exception handling. If `TransportError` is not enough, let's add others

2023-02-13 09:46 UTC, Michal-Kolomanski commented on transform/Pipfile
> -python_full_version = "3.10.5"
Please revert those changes, they are not in the scope

2023-02-13 09:46 UTC, Michal-Kolomanski commented on transform/Pipfile.lock
> +            "sha256": "7fa9536461fcb4880f7c56ec5fc6bb3dea620dd7cfda91fd123d8b1a4b79989a"
Please revert those changes, they are not in the scope

2023-02-13 11:30 UTC, eldenkat commented
Why a strict match doesn't go first?

![2023-02-13 (3)](https://user-images.githubusercontent.com/113451713/218446354-6bf2813d-e2e9-47bf-b0fd-d71d1a55cf59.png)

2023-02-13 13:53 UTC, eldenkat commented
Highlights.
Entering "horizontal service", page 1-4 highlights word "service", page 6 - no higlights and than returning to the page one by one 5,4,3,2,1 - no highlights.

![2023-02-13 (12)](https://user-images.githubusercontent.com/113451713/218475949-5d038812-d64e-4cd9-b2e8-e3e0a4cdd105.png)
![2023-02-13 (11)](https://user-images.githubusercontent.com/113451713/218475973-961c4472-b4ba-4640-b2a0-dd1b4bcd3059.png)
![2023-02-13 (10)](https://user-images.githubusercontent.com/113451713/218475982-ced0d5b3-b554-42f3-9747-7e8732f22220.png)

2023-02-24 07:41 UTC, Marcelinna approved these changes

2023-02-24 08:00 UTC, eldenkat approved these changes

2023-02-24 08:30 UTC, merged