ref: [#721] Replace Starlette config with Pydantic settings
cyfronet-fid/eosc-search-service pull request #724
Opened 2023-07-12 10:13 UTC by maria-j-k

2023-07-12 11:33 UTC, tomaszandel approved these changes

2023-07-14 13:09 UTC, michal-szostak requested changes
It is good generally - there are a few things that can be improved to make it a little bit less "hacky". All in all good job.

2023-07-14 13:09 UTC, michal-szostak commented on backend/app/settings.py
> +        config.OIDC_AUTH_ENDPOINT = OIDC_NEW_AUTH_ENDPOINT
It would be more elegant to move this code into `GlobalSettings` class itself - this kind of hacking can be done using validators (check `pre=True`)

2023-07-14 13:09 UTC, michal-szostak commented on backend/app/settings.py
> +            "STOMP_SSL": {"env": "ESS_STOMP_SSL"},
When overriding default names of env variables I'd suggest using declarative approach with `Field`:

```
STOMP_USER_ACTIONS_TOPIC = Field("/topic/user_actions", env="ESS_STOMP_USER_ACTION")
```

This way the name of the variable is in the same place as the variable declaration which might help avoid confusion.

2023-07-17 13:42 UTC, michal-szostak approved these changes

2023-07-17 14:36 UTC, merged