789 790 cite and export result
cyfronet-fid/eosc-search-service pull request #849
Opened 2023-09-01 15:27 UTC by maria-j-k

2023-09-12 16:19 UTC, Marcelinna commented
Why do we have two Harvard?
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/59872096/3e5d80c0-808d-4a40-ae81-79518de97981)

2023-09-12 16:26 UTC, Marcelinna commented
why are some links grayed out?
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/59872096/29eb84d9-0f43-4d6d-8b89-4a345ba83f6a)

2023-09-18 11:43 UTC, tomaszandel approved these changes

2023-09-18 11:44 UTC, tomaszandel commented
please fix lint always before submitting PR

2023-09-18 11:54 UTC, Marcelinna commented
we shouldn't squash commits?

2023-09-18 12:00 UTC, agpul approved these changes

2023-09-18 12:07 UTC, Michal-Kolomanski requested changes

2023-09-18 12:07 UTC, Michal-Kolomanski commented on ui/apps/ui/src/app/components/bibliography/styles.txt
> +    nazwisko, inicjał imienia.
Not sure what exactly is this file. And why is it in part Polish;p

2023-09-18 12:11 UTC, Michal-Kolomanski commented on backend/app/routes/web/bibliography.py
> +        pid(str): DOI of a publication to fetch the data for.
It was confirmed with @agpul. In the future, all PIDs will be used. Currently, only DOI is good enough.

2023-09-18 12:12 UTC, Michal-Kolomanski commented on backend/app/routes/web/bibliography.py
> +        pid(str): DOI of a publication to fetch the data for.
So change  pid(str): DOI of a publication to fetch the data for. ->  pid(str): PID of a publication to fetch the data for (currently only DOI)

2023-09-18 12:12 UTC, Michal-Kolomanski commented on backend/app/routes/web/bibliography.py
> +        pid(str): DOI of a publication to fetch the data for.
And please do so everywhere

2023-09-18 12:13 UTC, Michal-Kolomanski commented on backend/app/routes/web/bibliography.py
> +            _get_bibliography_record(pid=pid, entry_format=entry_format)
Ok, so this approach is fine for now. In the future it will be changed to handle all pids at once

2023-09-18 13:02 UTC, maria-j-k commented on backend/app/routes/web/bibliography.py
> +        pid(str): DOI of a publication to fetch the data for.
Currently we have only doi function, for other pids we would have to find another API's to get the metadata. 
if we itroduce other pids, we would need to have PID parameter and PID_TYPE or something similar and than call a proper function respectively to pid_type

2023-09-18 13:05 UTC, maria-j-k commented on ui/apps/ui/src/app/components/bibliography/bibliography.component.ts
> +        this.citationEmptyMessage =
No, it's a different message

2023-09-18 14:35 UTC, Michal-Kolomanski approved these changes
Not all comments have been resolved but here is my approval

2023-09-18 14:46 UTC, merged